CREATE TABLE MANAGERS(
	Regid Number PRIMARY KEY NOT NULL,
	REGION VARCHAR2(10) CONSTRAINT Chk_Region CHECK (REGION IN ('East', 'Central', 'West', 'South')),
	REGMANAGER VARCHAR2(10)
);

CREATE TABLE PRODUCTS(
	PRODID NUMBER PRIMARY KEY NOT NULL,
	PRODNAME VARCHAR2(100) NOT NULL,
	PRODCAT VARCHAR2(30) NOT NULL CONSTRAINT Chk_prodcat CHECK(PRODCAT IN ('Technology', 'Furniture', 'Office Supplies')),
	PRODSUBCAT VARCHAR2(30) NOT NULL,
	PRODCONT VARCHAR2(20)NOT NULL CONSTRAINT Chk_prodcont CHECK(PRODCONT IN ('Jumbo Drum', 'Medium Box', 'Jumbo Box', 'Wrap Bag', 'Large Box', 'Small Box', 'Small Pack')),
	PRODUNITPRICE NUMBER(7,2),
	PRODMARGIN NUMBER(5,3)
);

CREATE TABLE ORDERS(
	ORDERID NUMBER PRIMARY KEY NOT NULL,
	STATUS VARCHAR2(10)
);

CREATE TABLE CUSTOMERS(
	CUSTID NUMBER PRIMARY KEY NOT NULL,
	CUSTNAME VARCHAR2(35),
	CUSTREG NUMBER(1,0) REFERENCES MANAGERS(Regid) ON DELETE CASCADE,
	CUSTSTATE VARCHAR2(20),
	CUSTCITY VARCHAR2(20),
	CUSTZIP NUMBER(5,0),
	CUSTSEG VARCHAR2(15) CONSTRAINT Chk_custseg CHECK (CUSTSEG IN ('Home Office', 'Corporate', 'Small Business', 'Consumer'))
);

CREATE TABLE ORDERDET(
	ORDERID NUMBER NOT NULL REFERENCES ORDERS(ORDERID),
	CUSTID NUMBER NOT NULL REFERENCES CUSTOMERS(CUSTID),
	PRODID NUMBER NOT NULL REFERENCES PRODUCTS(PRODID),
	ORDPRIORITY VARCHAR2(15) CONSTRAINT Chk_priority CHECK (ORDPRIORITY IN ('Low', 'Medium', 'High', 'Critical', 'Not Specified')),
	ORDDISCOUNT NUMBER(3,2),
	ORDSHIPMODE VARCHAR2(15) CONSTRAINT Chk_ship CHECK (ORDSHIPMODE IN ('Regular Air', 'Delivery Truck', 'Express Air')),
	ORDDATE DATE,
	ORDSHIPDATE DATE,
	ORDSHIPCOST NUMBER(5,2),
	ORDQTY NUMBER,
	ORDSALES NUMBER(8,2),
	PRIMARY KEY(ORDERID, CUSTID, PRODID)	
);

